<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Abhishek Bansal" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../../../../img/favicon.ico">
    <title>Final Project Blog</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../../../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../../../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../../../../post/">BLOG</a></li>
        
        <li><a href="../../../../../projects/">PROJECTS</a></li>
        
        <li><a href="../../../../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../../../../post/2020/12/10/final-project-blog/">Final Project Blog</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         December 10, 2020 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="python-code-example-finding-summary-statistics-in-python" class="section level2">
<h2>Python Code Example: Finding Summary Statistics in Python</h2>
<p>Similar to R, python can be used to find summary statistics of a certain variable in a dataset. This can be helpful because the summary statistics provide helpful data which can be used in further studies. Below is an example using pandas to obtain the dataset and numpy in order to find summary statistics such as the minimum, maximum, mean, and median values for the variables mag and depth from the quakes dataset.</p>
<pre class="python"><code>import pandas as pd
quakes=pd.read_csv(&quot;https://vincentarelbundock.github.io/Rdatasets/csv/datasets/quakes.csv&quot;,index_col=0)

import numpy as np
quakes[&quot;mag&quot;].describe()</code></pre>
<pre><code>## count    1000.000000
## mean        4.620400
## std         0.402773
## min         4.000000
## 25%         4.300000
## 50%         4.600000
## 75%         4.900000
## max         6.400000
## Name: mag, dtype: float64</code></pre>
<pre class="python"><code>quakes[&quot;depth&quot;].describe()</code></pre>
<pre><code>## count    1000.000000
## mean      311.371000
## std       215.535498
## min        40.000000
## 25%        99.000000
## 50%       247.000000
## 75%       543.000000
## max       680.000000
## Name: depth, dtype: float64</code></pre>
<p>As you can see, finding the summary statistics in python is not that much harder than finding the same statistics in R! From the output, the mininium, maximum, mean, and meadian for magnitude is 4, 6.4, 4.6204, and 4.6, respectively. The mininium, maximum, mean, and median for depth is 40, 680, 311.371, and 247, respectively. These statistics provide a broader understanding of the variables magand depth from the quakes dataset.</p>
</div>
<div id="reticulate" class="section level2">
<h2>Reticulate</h2>
<p>One of the fascinating abilities of code is its ability to reticulate, or for it to actually talk to each other! In the example below, the reticulate package is loaded in R first. Once this package is loaded, certain phrases can be assigned to certain variables in R as well as in python (see example below). After these variables are assigned, another line of code in python can be used to construct the entire sentence (combining python and R code chunks)! An example is presented below:</p>
<pre class="r"><code>library(reticulate)
a&lt;-&quot;Python and R&quot;</code></pre>
<pre class="python"><code>b=&quot;are so fun&quot;
print(r.a,b)</code></pre>
<pre><code>## Python and R are so fun</code></pre>
<p>Here is a funny image that I found showing how python and R are both superior to excel!</p>
<img src="../../../../../post/2020-12-10-final-project-blog_files/image%20for%20project.jpg" style="width:75.0%" />
</center>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../../../../js/docs.min.js"></script>
<script src="../../../../../js/main.js"></script>

<script src="../../../../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
